# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca07e05cde8c0a86154df7e10adf633349e7ad3b3ff959a45c0fc1c35d1623d17fd61816ad8eafa4d909da2d147d9619796a2d72b9c7cf1d2b5826a374cea960

test:
  secret_key_base: f8cd1c58070842711a859f49cb5d3694cb73fa6a19772b9ed96c77d4f91b0e0adf40c09e28b0e012d92e530e167e73d1935c8492b47e24e90d6fec76dbf68314

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
